FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY controller ./controller
COPY service ./service
EXPOSE 7500

CMD ["python", "app.py"]